// Assets/game_images.h
//
// Public surface that ZypherUI.cpp uses to look up game cover images.
// The actual byte arrays live in game_images_data.h, which is
// auto-generated by embed_images.ps1 from PNG sources.
//
// Naming convention: each input PNG file basename (lowercased) becomes
// a pair of symbols — g_<name>_data[] (the bytes) and g_<name>_size
// (sizeof in bytes). game_images_data.h is included here so callers
// only need a single header.
//
// First-time setup:
//   1. Drop dbd.png, apex.png, dayz.png into this Assets/ folder.
//   2. Open PowerShell in this folder:
//        pwsh -File embed_images.ps1 dbd.png apex.png dayz.png
//   3. Rebuild the solution. The images are now baked into the EXE.

#pragma once

#include "game_images_data.h"

namespace GameImages {

    struct Bytes { const unsigned char* data; size_t size; };

    // Returns the byte view for a game id. Empty bytes mean no image
    // was embedded for that game — the UI falls back to a placeholder.
    inline Bytes For(const char* id) {
#if defined(GORDO_HAVE_GAME_IMAGE_DBD)
        if (strcmp(id, "dbd")  == 0) return { g_dbd_data,  g_dbd_data_size  };
#endif
#if defined(GORDO_HAVE_GAME_IMAGE_APEX)
        if (strcmp(id, "apex") == 0) return { g_apex_data, g_apex_data_size };
#endif
#if defined(GORDO_HAVE_GAME_IMAGE_DAYZ)
        if (strcmp(id, "dayz") == 0) return { g_dayz_data, g_dayz_data_size };
#endif
#if defined(GORDO_HAVE_GAME_IMAGE_RUST)
        if (strcmp(id, "rust") == 0) return { g_rust_data, g_rust_data_size };
#endif
        return { nullptr, 0 };
    }

}  // namespace GameImages
